#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom agricolae duncan.test
#' @importFrom ape pcoa
#' @importFrom broom tidy
#' @importFrom chemhelper get_scores
#' @importFrom clusterProfiler enricher
#' @importFrom DESeq2 DESeq
#' @importFrom DESeq2 DESeqDataSetFromMatrix
#' @importFrom DESeq2 results
#' @importFrom dplyr %>%
#' @importFrom dplyr arrange
#' @importFrom dplyr count
#' @importFrom dplyr inner_join
#' @importFrom dplyr lag
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr slice_max
#' @importFrom factoextra get_eigenvalue
#' @importFrom FactoMineR PCA
#' @importFrom forcats as_factor
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 arrow
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_fill
#' @importFrom ggplot2 rel
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 unit
#' @importFrom ggprism guide_prism_offset_minor
#' @importFrom ggrepel geom_label_repel
#' @importFrom ggsci scale_color_d3
#' @importFrom ggtext element_markdown
#' @importFrom ggthemes theme_foundation
#' @importFrom janitor clean_names
#' @importFrom lefser lefser
#' @importFrom magrittr set_names
#' @importFrom mixOmics splsda
#' @importFrom multcomp cld
#' @importFrom multcomp glht
#' @importFrom multcomp mcp
#' @importFrom normentR simulateGWAS
#' @importFrom purrr map
#' @importFrom purrr map_dbl
#' @importFrom rlang sym
#' @importFrom ropls opls
#' @importFrom rstatix wilcox_test
#' @importFrom scales percent
#' @importFrom stats anova
#' @importFrom stats aov
#' @importFrom stats IQR
#' @importFrom stats quantile
#' @importFrom stats reorder
#' @importFrom stringr str_replace
#' @importFrom stringr str_split
#' @importFrom SummarizedExperiment SummarizedExperiment
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom vegan adonis
#' @importFrom vegan decostand
#' @importFrom vegan envfit
#' @importFrom vegan rda
#' @importFrom vegan scores
#' @importFrom vegan vegdist
#' @importFrom WGCNA corAndPvalue
## usethis namespace: end
NULL
